# Generated by Django 4.1.6 on 2023-02-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='emp_id',
        ),
    ]
